server:
  port: 9999
spring:
  application:
    name: TEST_SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
    config:
      enabled: true
      fail-fast: true
      username: myUsername
      password: mySecretPassword
      override-system-properties: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
