server:
  port: 8081
spring:
  application:
    name: MANUFACTURE_SERVICE
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5433/manufacture_db}
    username: admin
    password: admin
  liquibase:
    enabled: true
    change-log: classpath:/db/main-changelog.xml
    default-schema: public
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5433/manufacture_db}
    user: admin
    password: admin
logging:
  level:
    org.springframework.data.r2dbc: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30